AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - '**/Gemfile'

Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/SymbolArray:
  Enabled: false
