development:
  adapter: postgresql
  database: website_mariette_dev
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  username:
  password:

production:
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
